[package]
name = "ckb-probe-ebpf"
version = "0.1.0"
edition = "2021"

# Build with:
#   cargo +nightly build --target bpfel-unknown-none -Z build-std=core

[[bin]]
name = "ckb-probe-ebpf"
path = "src/main.rs"

[dependencies]
aya-ebpf = "0.1"
aya-log-ebpf = "0.1"
ckb-probe-common = { path = "../ckb-probe-common", default-features = false }

[profile.dev]
opt-level = 2
overflow-checks = false
debug = false
panic = "abort"

[profile.release]
lto = true
panic = "abort"
